name: IAC Dev

on:
  workflow_dispatch:

permissions:
  id-token: write     
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/infra-pipeline.yml
    with:
      env: dev
      iac_tool: terraform
    secrets: inherit
